using System;
using System.Collections.Generic;
using System.Linq;

/// <summary>
/// Represents a consumer as a multidimensional profile vector.
/// Contains a collection of <see cref="DimensionValue"/> entries that describe
/// the consumer's preferences, needs, and psychological characteristics.
/// </summary>
/// <remarks>
/// <para>
/// This profile is typically generated by the RuleEngine, which processes input data such as:
/// <list type="bullet">
///   <item><description>Personal identification (DNI/ID)</description></item>
///   <item><description>Economic data (salary, income level)</description></item>
///   <item><description>Psychological profile (personality traits, behaviors)</description></item>
///   <item><description>Purchase history and preferences</description></item>
/// </list>
/// </para>
/// <para>
/// The profile serves as a mathematical representation of the consumer,
/// enabling comparison with product profiles for matching and recommendation purposes.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// var profile = new ConsumerProfile();
/// profile.Set(priceSensitivityDef, 0.76f);
/// profile.Set(qualityExpectationDef, 0.60f);
/// profile.Set(socialRecognitionDef, 0.40f);
/// profile.Set(easeOfUseDef, 0.50f);
/// 
/// // Retrieve a specific dimension
/// var priceValue = profile.Get(priceSensitivityDef);
/// Console.WriteLine($"Price sensitivity: {priceValue?.Value}");
/// </code>
/// </example>
public class ConsumerProfile
{
  /// <summary>
  /// Gets the dictionary mapping dimension definitions to their corresponding values.
  /// Each entry represents one aspect of the consumer's profile.
  /// </summary>
  public Dictionary<DimensionDefinition, DimensionValue> Dimensions { get; }

  /// <summary>
  /// Initializes a new empty consumer profile.
  /// Dimensions must be added using the <see cref="Set"/> method.
  /// </summary>
  public ConsumerProfile()
  {
    Dimensions = new Dictionary<DimensionDefinition, DimensionValue>();
  }

  /// <summary>
  /// Sets or updates a dimension value in the profile.
  /// If the dimension already exists, it will be replaced.
  /// </summary>
  /// <param name="def">The dimension definition to set</param>
  /// <param name="value">The normalized value (0–1, automatically clamped)</param>
  /// <exception cref="ArgumentNullException">Thrown when def is null</exception>
  /// <example>
  /// <code>
  /// profile.Set(brandLoyaltyDef, 0.85f);  // High brand loyalty
  /// profile.Set(innovationSeekingDef, 0.30f);  // Low interest in new products
  /// </code>
  /// </example>
  public void Set(DimensionDefinition def, float value)
  {
    if (def == null)
      throw new ArgumentNullException(nameof(def));

    Dimensions[def] = new DimensionValue(def, value);
  }

  /// <summary>
  /// Retrieves the dimension value for a specific definition.
  /// </summary>
  /// <param name="def">The dimension definition to look up</param>
  /// <returns>The dimension value if found, otherwise null</returns>
  /// <example>
  /// <code>
  /// var qualityValue = profile.Get(qualityExpectationDef);
  /// if (qualityValue != null)
  /// {
  ///     Console.WriteLine($"Quality expectation: {qualityValue.Value}");
  /// }
  /// </code>
  /// </example>
  public DimensionValue Get(DimensionDefinition def)
  {
    return Dimensions.TryGetValue(def, out var value) ? value : null;
  }

  /// <summary>
  /// Checks if the profile contains a specific dimension.
  /// </summary>
  /// <param name="def">The dimension definition to check</param>
  /// <returns>True if the dimension exists in the profile, false otherwise</returns>
  public bool HasDimension(DimensionDefinition def)
  {
    return def != null && Dimensions.ContainsKey(def);
  }

  /// <summary>
  /// Modifies an existing dimension value by adding a delta.
  /// If the dimension doesn't exist, it will be created with the delta as initial value.
  /// </summary>
  /// <param name="def">The dimension definition to modify</param>
  /// <param name="delta">The amount to add (can be negative)</param>
  /// <exception cref="ArgumentNullException">Thrown when def is null</exception>
  /// <example>
  /// <code>
  /// // Increase price sensitivity after seeing a discount
  /// profile.Adjust(priceSensitivityDef, 0.15f);
  /// 
  /// // Decrease social recognition need after mature reflection
  /// profile.Adjust(socialRecognitionDef, -0.20f);
  /// </code>
  /// </example>
  public void Adjust(DimensionDefinition def, float delta)
  {
    if (def == null)
      throw new ArgumentNullException(nameof(def));

    if (Dimensions.TryGetValue(def, out var existing))
    {
      existing.Add(delta);
    }
    else
    {
      Dimensions[def] = new DimensionValue(def, delta);
    }
  }

  /// <summary>
  /// Returns all dimension values as a read-only collection.
  /// Useful for iteration and analysis.
  /// </summary>
  /// <returns>A collection of all dimension values in the profile</returns>
  public IEnumerable<DimensionValue> GetAllValues()
  {
    return Dimensions.Values;
  }

  /// <summary>
  /// Gets the number of dimensions in this profile.
  /// </summary>
  public int Count => Dimensions.Count;

  /// <summary>
  /// Returns a string representation of the profile for debugging.
  /// </summary>
  /// <example>
  /// Output example:
  /// <code>
  /// ConsumerProfile (4 dimensions):
  ///   PriceSensitivity = 0.76
  ///   QualityExpectation = 0.60
  ///   SocialRecognition = 0.40
  ///   EaseOfUse = 0.50
  /// </code>
  /// </example>
  public override string ToString()
  {
    var dimensions = string.Join("\n  ",
      Dimensions.Values.Select(dv => $"{dv.Definition.Name} = {dv.Value:F2}"));
    return $"ConsumerProfile ({Count} dimensions):\n  {dimensions}";
  }
}